### ISSUE TITLE
Define as multiline.

### ISSUE THREAD

**Issue by flukejones** [Firstyear/cargo-packaging#1]
To be on the safe side,

https://github.com/Firstyear/cargo-packaging/blob/aa84b32a0b2245c9841bf707f951ede7e9d3bae6/macros.cargo#L2

should be split as multiline like:

```spec
%if %{defined fedora}
%global debug_package %{nil}
%endif
```

I'm actually unsure of effect as single line, but someone somewhere will nitpick it as single-line at least.

**Comment by Firstyear** [comment]
Fixed :)

**Comment by Firstyear** [comment]
Actually, should this actually be in the .spec file? It looks like fedora is failing to build the package without a debug pkg? @flukejones
